version: '3.8'

services:
  frontend:
    image: blogging-platform-frontend:latest
    container_name: blogging-platform-frontend-1
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - NODE_ENV=production
    networks:
      - bloggify-network
    restart: unless-stopped

  backend:
    image: blogging-platform-backend:latest
    container_name: blogging-platform-backend-1
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGO_URI=${MONGO_URI}
      - JWT_KEY=${JWT_KEY}
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
      - NODE_ENV=production
      - SENDGRID_API_KEY=${SENDGRID_API_KEY}
    networks:
      - bloggify-network
    restart: unless-stopped

networks:
  bloggify-network:
    driver: bridge