name: Deploy to Azure App Service

on:
  push:
    branches:
      - deployment
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Log in to Azure Container Registry
      uses: docker/login-action@v2
      with:
        registry: bloggifyregistry-eubcfchxcyfzgxfa.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    
    # Frontend deployment
    - name: Build and push Frontend Docker image
      uses: docker/build-push-action@v4
      with:
        context: ./Frontend
        push: true
        tags: bloggifyregistry-eubcfchxcyfzgxfa.azurecr.io/bloggify-frontend:latest
    
    - name: Deploy Frontend to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'bloggify-frontend'
        images: 'bloggifyregistry-eubcfchxcyfzgxfa.azurecr.io/bloggify-frontend:latest'
    
    # Backend deployment
    - name: Build and push Backend Docker image
      uses: docker/build-push-action@v4
      with:
        context: ./Backend
        push: true
        tags: bloggifyregistry-eubcfchxcyfzgxfa.azurecr.io/bloggify-backend:latest
    
    - name: Deploy Backend to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'bloggify-backend'
        images: 'bloggifyregistry-eubcfchxcyfzgxfa.azurecr.io/bloggify-backend:latest'